"""empty message

Revision ID: 197bba1c1835
Revises: c23ef1523b10
Create Date: 2019-05-12 16:36:34.440124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197bba1c1835'
down_revision = 'c23ef1523b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_rule_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roleid', sa.Integer(), nullable=True),
    sa.Column('ruleid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roleid'], ['tbl_role.id'], ),
    sa.ForeignKeyConstraint(['ruleid'], ['tbl_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_rule_role')
    # ### end Alembic commands ###
