"""empty message

Revision ID: c23ef1523b10
Revises: 8b1615cd3d50
Create Date: 2019-05-11 11:56:52.119135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23ef1523b10'
down_revision = '8b1615cd3d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user', sa.Column('roleid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_user', 'tbl_role', ['roleid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_user', type_='foreignkey')
    op.drop_column('tbl_user', 'roleid')
    # ### end Alembic commands ###
